services:
  gym-db-postgres:
    image: docker.io/library/postgres:18.3
    container_name: gym-db-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
    volumes:
      - gym_db_pgsql:/var/lib/postgresql/18/main

  gym-app:
    image: gym_ws:1.0
    container_name: gym-ws-pg
    depends_on:
      - gym-db-postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: pg
      POSTGRES_HOST: gym-db-postgres

volumes:
  gym_db_pgsql: